# Generated by Django 3.1.4 on 2020-12-31 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20201231_1916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='gategories',
            new_name='categories',
        ),
        migrations.AddField(
            model_name='post',
            name='featured',
            field=models.BooleanField(default=0),
        ),
    ]
