# Generated by Django 3.1.4 on 2021-01-01 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20210101_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='previous_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='posts.post'),
        ),
    ]
