# Generated by Django 3.1.4 on 2021-01-03 09:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0014_posyview'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PosyView',
            new_name='PostView',
        ),
        migrations.RemoveField(
            model_name='post',
            name='view_count',
        ),
    ]
